site_name: SID's Wiki
site_url: https://wiki.sidkang.com/

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  direction: ltr
  features:
    # - header.autohide
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    # - header.autohide
    - navigation.top

extra_css:
  - assets/stylesheets/basic.css
  - assets/stylesheets/utterances.css

plugins:
  - awesome-pages:
      filename: .index
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
  - macros:
      include_dir: snippets
      module_name: macro
  - search:
      lang: ja
  - mermaid2

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/sidkang
      name: SidKang
  generator: false

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.critic:  # formatting
      mode: view
  - pymdownx.betterem:  # better markup for emphasize
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - toc:
      permalink: True
      toc_depth: 3
  - pymdownx.highlight:
      use_pygments: True
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      base_path: ['.', 'docs']
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.magiclink
  - pymdownx.saneheaders
  # - pymdownx.pathconverter

  - pymdownx.progressbar
  - markdown.extensions.meta
  - markdown.extensions.attr_list
  - pymdownx.b64 # erwer


# available_metadata:
# - comment: true or false, for comment system
# - title: title used in navigation
