name: publish
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.x
      - run: pip install -U pip wheel
      - run: pip install -U -r requirements.txt
      - run: mkdocs gh-deploy --force